version: '3.8'

services:
  pyro-ns:
    container_name: pyro-ns
    build:
      context: ./pyro
      dockerfile: Dockerfile
    working_dir: /home
    ports:
      - "8020:8020"
    networks:
      - main_network

  server:
    container_name: server
    build:
      context: ./server
      dockerfile: Dockerfile
    working_dir: /home
    depends_on:
      - pyro-ns
    networks:
      - main_network
    volumes:
      - ./server/files/database:/home/database

  client-thui:
    container_name: thui
    build:
      context: ./client
      dockerfile: Dockerfile
    environment:
      - CONTAINER_NAME=thui
      - DISPLAY=$DISPLAY
      - CLIENT_NAME=Thui
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    working_dir: /home
    depends_on:
      - pyro-ns
    networks:
      - main_network

  client-bija:
    container_name: bija
    build:
      context: ./client
      dockerfile: Dockerfile
    environment:
      - CONTAINER_NAME=bija
      - DISPLAY=$DISPLAY
      - CLIENT_NAME=Bija
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    working_dir: /home
    depends_on:
      - pyro-ns
    networks:
      - main_network

  client-patic:
    container_name: patic
    build:
      context: ./client
      dockerfile: Dockerfile
    environment:
      - CONTAINER_NAME=patic
      - DISPLAY=$DISPLAY
      - CLIENT_NAME=Patic
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    working_dir: /home
    depends_on:
      - pyro-ns
    networks:
      - main_network

networks:
  main_network:
    driver: bridge
