services:
  server:
    container_name: server
    build:
      context: ./server
      dockerfile: Dockerfile
    working_dir: /home
    ports:
      - "8020:8020"
    networks:
      - main_network

  client-alice:
    container_name: thui
    build:
      context: ./client
      dockerfile: Dockerfile
    environment:
      - DISPLAY=$DISPLAY
      - CLIENT_NAME=Alice
    working_dir: /home
    networks:
      - main_network
    depends_on:
      - server

  client-bob:
    container_name: bija
    build:
      context: ./client
      dockerfile: Dockerfile
    environment:
      - DISPLAY=$DISPLAY
      - CLIENT_NAME=Bob
    working_dir: /home
    networks:
      - main_network
    depends_on:
      - server

networks:
  main_network:
    driver: bridge
