services:

  server:
    container_name: server
    build:
      context: ./server
      dockerfile: Dockerfile
    command: ["python", "-m", "Pyro5.nameserver", "--host", "0.0.0.0", "--port", "8020"]
    working_dir: /home
    ports:
      - "8020:8020"
    networks:
      - main_network
    volumes:
      - ./server/files/database:/home/database

  client-thui:
    container_name: thui
    build:
      context: ./client
      dockerfile: Dockerfile
    environment:
      - DISPLAY=$DISPLAY
      - CLIENT_NAME=Thui
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    working_dir: /home
    networks:
      - main_network


  client-bija:
    container_name: bija
    build:
      context: ./client
      dockerfile: Dockerfile
    environment:
      - DISPLAY=$DISPLAY
      - CLIENT_NAME=Bija
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    working_dir: /home
    networks:
      - main_network


  client-patic:
    container_name: patic
    build:
      context: ./client
      dockerfile: Dockerfile
    environment:
      - DISPLAY=$DISPLAY
      - CLIENT_NAME=Patic
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    working_dir: /home
    networks:
      - main_network


networks:
  main_network:
    driver: bridge
